- hosts: external
  become: true
  tasks:
  - include_vars:
      file: creds.yml
  - name: Ensure xfce (desktop) get installed
    apt:
      update_cache: yes
      force: yes
      name: ['xfce4', 'xfce4-goodies', 'xorg', 'dbus-x11', 'x11-xserver-utils']
      state: present
  - name: Ensure xrdp get installed
    apt:
      update_cache: yes
      force: yes
      name: ['xrdp']
      state: present
  - name: open rdp port
    command: sudo ufw allow 3389/tcp
  - name: set pw for techcafe
    user:
      name: "{{ user }}"
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"

 # - name:
  #  command: sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config