- name: Ensure terraform repository key is imported
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Ensure terraform repository is added
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com bionic main"
    update_cache: no
    state: present
  become: true

- name: Ensure TF is installed
  apt:    
    name: "terraform"
    update_cache: yes
    force: yes
    state: present
  become: true