- hosts: maxlocalpc
  become: true
  vars:
  - apt_file: /etc/apt/sources.list.d/google-chrome.list
  tasks:
  - name: Install VSCode   
    community.general.snap:
      name: code
      classic: yes
  
  - name: Ensure installation of zsh
    import_role:
      name: ohmyzsh
    tags: ohmyzsh
  
  - name: Ensure installation of ohmyzsh
    command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: Install Docker
    import_role:
      name: docker
    tags: docker
  
  - name: Install terraform
    import_role:
      name: terraform
    tags: terraform

  - name: Install kubectl   
    community.general.snap:
      name: kubectl
      classic: yes

  - name: Install ibmcloudcli
    import_role:
      name: ibmcloudcli
    tags: ibmcloudcli

  - name: Install Helm  
    community.general.snap:
      name: helm
      classic: yes
  
  - name: Install Node 
    community.general.snap:
      name: node
      classic: yes

  - name: Install WhatsDesk (WhatsApp)
    community.general.snap:
      name: whatsdesk
  
  - name: Install Chrome Browser
    import_role:
      name: chrome
    tags: chrome

  - name: Install nvidia-driver
    import_role:
      name: nvidia-driver
    tags: nvidia-driver

  # - name: install NVidiadriver

  # - name: install nvidia container runtime

  # - name: install nvidia container toolkit

  # - name: install nvidia container runtime


  
